<a href="https://colab.research.google.com/github/chakrishabad-23/DSA/blob/main/pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

###`Q-1:` Write a program to create an empty series.

In [3]:
# code here
pd.Series([])

Series([], dtype: object)

###`Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [4]:
# code here
chakri=pd.Series([1,2,3,4,5])
k=pd.Series([1,2,3,4,5])

In [9]:
chakri//k

0    1
1    1
2    1
3    1
4    1
dtype: int64

###`Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [12]:
# code here
p1=pd.Series([2, 4, 6, 8, 10])
p2=pd.Series( [1, 3, 5, 7, 10])

In [18]:
p1[p1-1==p2]

0    2
1    4
2    6
3    8
dtype: int64

###`Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [22]:
# code here
def Series(series,dtypes):
  series=series.astype(dtypes)
  return series
marks=pd.Series([1,2,3,4,5])
marks.dtype
Series(marks,'int32').dtype

dtype('int32')

Download data - https://drive.google.com/file/d/1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb/view?usp=share_link
All Batsman runs series in IPL 2008 to 2022.

Below questions are based on this data.

###`Q-6` Find top 10 most run getter from the series.

In [23]:
# code here
series=pd.read_csv('/content/batsman_runs_series.csv')

In [37]:
series=series.squeeze()
series.sort_values(by='batsman_run',ascending=False).head(10)[['batter','batsman_run']]

             batter  batsman_run
569         V Kohli         6634
462        S Dhawan         6244
130       DA Warner         5883
430       RG Sharma         5881
493        SK Raina         5536
27   AB de Villiers         5181
108        CH Gayle         4997
339        MS Dhoni         4978
452      RV Uthappa         4954
256      KD Karthik         4377

###`Q-7` No of players having runs above 3000

In [42]:
# code here
series[series['batsman_run']>3000].sort_values(by='batsman_run')

             batter  batsman_run
597       YK Pathan         3222
169    F du Plessis         3403
251      KA Pollard         3437
519       SV Samson         3526
328       MK Pandey         3657
511       SR Watson         3880
263        KL Rahul         3895
46        AM Rahane         4074
60        AT Rayudu         4190
174       G Gambhir         4217
256      KD Karthik         4377
452      RV Uthappa         4954
339        MS Dhoni         4978
108        CH Gayle         4997
27   AB de Villiers         5181
493        SK Raina         5536
430       RG Sharma         5881
130       DA Warner         5883
462        S Dhawan         6244
569         V Kohli         6634

###`Q-8` No of players having runs above mean value?

In [53]:
series[series['batsman_run']>series['batsman_run'].mean()].count()

batter         128
batsman_run    128
dtype: int64

Download data - https://drive.google.com/file/d/1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd/view?usp=share_link

file name - items.csv

###`Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series


How csv file looks

```
item_name	item_price
Chips and Fresh Tomato Salsa	$2.39
Izze	$3.39
Nantucket Nectar	$3.39
Chips and Tomatillo-Green Chili Salsa	$2.39
Chicken Bowl	$16.98

```

In [84]:
# code here
items=pd.read_csv('/content/items.csv',index_col='item_name')
items

                                      item_price
item_name
Chips and Fresh Tomato Salsa              $2.39
Izze                                      $3.39
Nantucket Nectar                          $3.39
Chips and Tomatillo-Green Chili Salsa     $2.39
Chicken Bowl                             $16.98
...                                          ...
Steak Burrito                            $11.75
Steak Burrito                            $11.75
Chicken Salad Bowl                       $11.25
Chicken Salad Bowl                        $8.75
Chicken Salad Bowl                        $8.75

[4622 rows x 1 columns]

In [95]:
items['item_price'] = (
    items['item_price']
    .fillna("$0")  # Replace NaN with a placeholder string
    .astype(str)
    .str.replace("$", "", regex=False)
    .astype(float) * 80
)
print(type(items))

<class 'pandas.core.frame.DataFrame'>

###`Q-10`:
    i. Find mean price
    ii. Find 30th and 6th percentile value
    iii. Plot Histogram on price with bin size 50
    iv. No of items price lies between [1000 to 2000]

In [ ]:
# code here